### PR TITLE
fix missing compaction parts

### LINKED ISSUE #584: why the test case " Benchmark_Table_Insert_100Rows_100Iters_100Writers" cannot pass  tests?
Hi, frostdb is a great project, I use newest frostdb to benchmark table instert, i found  Benchmark_Table_Insert_100Rows_100Iters_100Writers(table_test.go) can't pass, output below wrong:
    table_test.go:278: 
        	Error Trace:	/media/vdc/workspace/src/github.com/polarsignals/frostdb/table_test.go:278
        	            				/media/vdc/workspace/src/github.com/polarsignals/frostdb/table_test.go:177
        	Error:      	Not equal: 
        	            	expected: 1000000
        	            	actual  : 528400
        	Test:       	Benchmark_Table_Insert_100Rows_100Iters_100Writers
--- FAIL: Benchmark_Table_Insert_100Rows_100Iters_100Writers-8

Benchmark_Table_Insert_1000Rows_10Iters_10Writers and Benchmark_Table_Insert_100Rows_1000Iters_1Writers  are passed

### PR DESCRIPTION
**Pull request by thorfour**
Fixes #584

### CODE REVIEW

File: parts/part.go [hunk 1]
```diff
@@ -334,6 +335,10 @@ func FindMaximumNonOverlappingSet(schema *dynparquet.Schema, parts []*Part) ([]*
 			// The current part must be removed. Don't update prevEnd or prev,
 			// this will be used in the next iteration and must stay the same.
 			overlapping = append(overlapping, parts[i])
+
+			if i == len(parts)-1 { // This is the last iteration mark this one as missing
+				missing = parts[prev]
```
Comment (asubiotto) [inline parts/part.go:340]: instead of adding a `missing` variable, why not just `overlapping = append(overlapping, parts[prev])` here?

Comment (thorfour) [reply parts/part.go:340]: I found that sometimes conflicted with the check below and caused the part to be double saved in some cases

**Review by asubiotto — APPROVED** [review]
